# Site settings
name: 邹晋
location: 浙江
company: 浙江万里学院
position: 学生
<img src="/123.jpg" width="100%">  
phone: xxxxxxxxx
email: xxxx@xxx.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

